### ISSUE TITLE
Cattery

### ISSUE THREAD

**Issue by aldmbmtl** [juno-fx/Terra-Official-Plugins#16]
It'd be great to be able to install Cattery files or other ML bundles directly into nuke.

https://community.foundry.com/cattery

**Comment by ddesmond** [comment]
Triplicates (or kinda related):
https://github.com/juno-fx/Terra-Official-Plugins/issues/39
https://github.com/juno-fx/Terra-Official-Plugins/issues/16
https://github.com/juno-fx/Terra-Official-Plugins/issues/12

I will leave just the 39 open, since that encompases all models available or listed from Foundry site.
