### ISSUE TITLE
Demo Files ALab files don't load in nuke

### ISSUE THREAD

**Issue by lamepennies** [juno-fx/Terra-Official-Plugins#82]
Not sure if I'm doing this wrong but the files in the ALab won't load in nuke. They are greyed out or say it's not compatible. 

![Image](https://github.com/user-attachments/assets/94eea429-fb82-4206-a73f-d84fb8a54637)

Maybe the files aren't the full size?

**Comment by ddesmond** [comment]
Clsoing this for now since this is not a real examplefor nuke but for blender and houdini or apps which can handle such large amount of data (this is a huge USD with hi res textures, animations, fx and all - you would need to load a specific setup of the usd to actualy make it work or load just the proxies and cameras.)

This pack is around 100gb in size, so yea i dont think this is doable like so.

Try open another USD file :)

closing as not relevant to the USD files itself.
